#Set base image from debian:stretch slim with R and python3 for running scRNAseq workflow on RIS compute1
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends vim git wget && apt-get clean

RUN wget 

#RUN git clone https://github.com/emnehls/SH_scRNAseq.git
#RUN R -e "install.packages('remotes', dependencies=TRUE, repos='http://cran.rstudio.com/')"
#RUN R -e "remotes::isntall_github('mojaveazure/seurat-disk')"
# RUN git clone
